name: Release Assets2

on:
  workflow_dispatch:
  # Workflow runs when a release is created in GitHub
  release:
    types: [published]

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: Release image & chart
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the image taged with the release tag, this is the semver taged release of the image
      - name: Build the Docker image
        run: docker buildx build --file ./build/Dockerfile --platform linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6 -t inerplat/kubeview --push .
